services:
  - type: web
    name: rotam-backend
    env: node
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 20
